### ISSUE TITLE
Websocket loading issue on Windows Server

### ISSUE THREAD

**Issue by manuelgu** [manuelgu/DiscordMC#11]
Possible fix: `Discord4J.disableAudio()`

```
java.lang.RuntimeException: Cannot call method public void sx.blah.discord.api.internal.DiscordWS#onMessage(org.eclipse.jetty.websocket.api.Session, byte[], int, int) with args: [org.eclipse.jetty.websocket.common.WebSocketSession, [B, java.lang.Integer, java.lang.Integer]
    at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.unwrapRuntimeException(CallableMethod.java:94)
    at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:76)
    at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:68)
    at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.onBinaryMessage(JettyAnnotatedEventDriver.java:124)
    at org.eclipse.jetty.websocket.common.message.SimpleBinaryMessage.messageComplete(SimpleBinaryMessage.java:68)
    at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:66)
    at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.onBinaryFrame(JettyAnnotatedEventDriver.java:116)
    at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:157)
    at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:376)
    at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:220)
    at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220)
    at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:256)
    at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:679)
    at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:511)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
    at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:202)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
    at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchFieldError: RESOURCE_PREFIX
    at sx.blah.discord.api.internal.Opus.getNative(Opus.java:30)
    at sx.blah.discord.api.internal.Opus.<clinit>(Opus.java:52)
    at sx.blah.discord.handle.audio.impl.AudioManager.getEncoderForChannels(AudioManager.java:135)
    at sx.blah.discord.handle.audio.impl.AudioManager.<init>(AudioManager.java:40)
    at sx.blah.discord.handle.impl.obj.Guild.<init>(Guild.java:120)
    at sx.blah.discord.handle.impl.obj.Guild.<init>(Guild.java:102)
    at sx.blah.discord.api.internal.DiscordUtils.getGuildFromJSON(DiscordUtils.java:243)
    at sx.blah.discord.api.internal.DiscordWS.guildCreate(DiscordWS.java:694)
    at sx.blah.discord.api.internal.DiscordWS.onMessage(DiscordWS.java:371)
    at sx.blah.discord.api.internal.DiscordWS.onMessage(DiscordWS.java:1117)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:71)
    ... 24 common frames omitted
```

**Comment by manuelgu** [comment]
This was fixed in https://github.com/manuelgu/DiscordMC/commit/a09429b3e122435229d98c7c8a99b6d83a7e2367
