### ISSUE TITLE
IOOB exception with /discord send

### ISSUE THREAD

**Issue by manuelgu** [manuelgu/DiscordMC#15]
```
[01:13:01] [Server thread/INFO]: silverforte issued server command: /discord send general 1
[01:13:01] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'discord' in plugin DiscordMC v1.4.9
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
    at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
    at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1344) [spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
    at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1179) [spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
    at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
    at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
    at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_121]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_121]
    at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
    at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
    at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
    at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
    at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_121]
    at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_121]
    at eu.manuelgu.discordmc.DiscordCommand.onCommand(DiscordCommand.java:149) ~[?:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
    ... 15 more
```

**Comment by manuelgu** [comment]
Likely to be fixed with https://github.com/manuelgu/DiscordMC/commit/58fd8735d7914f7145663b0b2db640546fb86745. User did not have the bot added to any guild by the looks of things.
