### ISSUE TITLE
 Error occurred while enabling DiscordMC v1.4.11-SNAPSHOT (Is it up to date?)

### ISSUE THREAD

**Issue by Joapple** [manuelgu/DiscordMC#23]
This happen on the server startup:
<details><summary>Show stack trace</summary><pre><code>
[10:46:40] [Server thread/INFO]: [DiscordMC] Enabling DiscordMC v1.4.11-SNAPSHOT
[10:46:41] [Server thread/WARN]: 2017-03-08 10:46:41.014:INFO::Server thread: Logging initialized @23767ms to org.eclipse.jetty.util.log.StdErrLog
[10:46:41] [Server thread/ERROR]: Error occurred while enabling DiscordMC v1.4.11-SNAPSHOT (Is it up to date?)
java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonFactory.requiresPropertyOrdering()Z
at com.fasterxml.jackson.databind.ObjectMapper.(ObjectMapper.java:564) ~[?:?]
at com.fasterxml.jackson.databind.ObjectMapper.(ObjectMapper.java:474) ~[?:?]
at sx.blah.discord.api.internal.DiscordUtils.(DiscordUtils.java:54) ~[?:?]
at sx.blah.discord.api.events.EventDispatcher.(EventDispatcher.java:28) ~[?:?]
at sx.blah.discord.api.internal.DiscordClientImpl.(DiscordClientImpl.java:118) ~[?:?]
at sx.blah.discord.api.ClientBuilder.build(ClientBuilder.java:199) ~[?:?]
at eu.manuelgu.discordmc.DiscordMC.onEnable(DiscordMC.java:124) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[patched_1.11.2.jar:git-Paper-1057]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.11.2.jar:git-Paper-1057]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.11.2.jar:git-Paper-1057]
at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:378) [patched_1.11.2.jar:git-Paper-1057]
at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:328) [patched_1.11.2.jar:git-Paper-1057]
at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:437) [patched_1.11.2.jar:git-Paper-1057]
at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:398) [patched_1.11.2.jar:git-Paper-1057]
at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:336) [patched_1.11.2.jar:git-Paper-1057]
at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:276) [patched_1.11.2.jar:git-Paper-1057]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:603) [patched_1.11.2.jar:git-Paper-1057]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[10:46:41] [Server thread/INFO]: [DiscordMC] Disabling DiscordMC v1.4.11-SNAPSHOT
[10:46:41] [Server thread/ERROR]: Error occurred while disabling DiscordMC v1.4.11-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException
at eu.manuelgu.discordmc.DiscordMC.onDisable(DiscordMC.java:164) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273) ~[patched_1.11.2.jar:git-Paper-1057]
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344) [patched_1.11.2.jar:git-Paper-1057]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:320) [patched_1.11.2.jar:git-Paper-1057]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.11.2.jar:git-Paper-1057]
at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:378) [patched_1.11.2.jar:git-Paper-1057]
at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:328) [patched_1.11.2.jar:git-Paper-1057]
at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:437) [patched_1.11.2.jar:git-Paper-1057]
at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:398) [patched_1.11.2.jar:git-Paper-1057]
at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:336) [patched_1.11.2.jar:git-Paper-1057]
at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:276) [patched_1.11.2.jar:git-Paper-1057]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:603) [patched_1.11.2.jar:git-Paper-1057]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
</code></pre></details>

**Comment by manuelgu** [comment]
Is this on *startup*?
Did you possibly reload via PlugMan?
Is this persistently occuring?

**Comment by Joapple** [comment]
This happen if i try to /plugman enable DiscordMC


This is from startup:
[10:46:40] [Server thread/INFO]: [DiscordMC] Enabling DiscordMC v1.4.11-SNAPSHOT
[10:46:41] [Server thread/WARN]: 2017-03-08 10:46:41.014:INFO::Server thread: Logging initialized @23767ms to org.eclipse.jetty.util.log.StdErrLog
[10:46:41] [Server thread/ERROR]: Error occurred while enabling DiscordMC v1.4.11-SNAPSHOT (Is it up to date?)
java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonFactory.requiresPropertyOrdering()Z
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:564) ~[?:?]
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:474) ~[?:?]
	at sx.blah.discord.api.internal.DiscordUtils.<clinit>(DiscordUtils.java:54) ~[?:?]
	at sx.blah.discord.api.events.EventDispatcher.<init>(EventDispatcher.java:28) ~[?:?]
	at sx.blah.discord.api.internal.DiscordClientImpl.<init>(DiscordClientImpl.java:118) ~[?:?]
	at sx.blah.discord.api.ClientBuilder.build(ClientBuilder.java:199) ~[?:?]
	at eu.manuelgu.discordmc.DiscordMC.onEnable(DiscordMC.java:124) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[patched_1.11.2.jar:git-Paper-1057]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.11.2.jar:git-Paper-1057]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.11.2.jar:git-Paper-1057]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:378) [patched_1.11.2.jar:git-Paper-1057]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:328) [patched_1.11.2.jar:git-Paper-1057]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:437) [patched_1.11.2.jar:git-Paper-1057]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:398) [patched_1.11.2.jar:git-Paper-1057]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:336) [patched_1.11.2.jar:git-Paper-1057]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:276) [patched_1.11.2.jar:git-Paper-1057]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:603) [patched_1.11.2.jar:git-Paper-1057]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[10:46:41] [Server thread/INFO]: [DiscordMC] Disabling DiscordMC v1.4.11-SNAPSHOT
[10:46:41] [Server thread/ERROR]: Error occurred while disabling DiscordMC v1.4.11-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException
	at eu.manuelgu.discordmc.DiscordMC.onDisable(DiscordMC.java:164) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273) ~[patched_1.11.2.jar:git-Paper-1057]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344) [patched_1.11.2.jar:git-Paper-1057]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:320) [patched_1.11.2.jar:git-Paper-1057]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.11.2.jar:git-Paper-1057]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:378) [patched_1.11.2.jar:git-Paper-1057]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:328) [patched_1.11.2.jar:git-Paper-1057]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:437) [patched_1.11.2.jar:git-Paper-1057]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:398) [patched_1.11.2.jar:git-Paper-1057]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:336) [patched_1.11.2.jar:git-Paper-1057]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:276) [patched_1.11.2.jar:git-Paper-1057]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:603) [patched_1.11.2.jar:git-Paper-1057]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

**Comment by Joapple** [comment]
I tried to plugman it, but plugman is been failing for many plugins anyway, so we're not really using it anymore only for unloading plugins only.. But i got the second stackstrace on startup, then try to enable it with plugman and get the 1st stacktrace. While on my creative server and my test server it works super fine.

**Comment by manuelgu** [comment]
It is not recommended to toggle DiscordMC with PlugMan, or by a global `/reload`.

**Comment by Joapple** [comment]
Okay, edited the issue to actually write what you want, the plugin fail to load on startup, so then i tried to plugman enable DiscordMC and it gave a class not found error, but no matter how many times i try to fully restart the server, the plugin won't load.

**Comment by Joapple** [comment]
Sorry if you misunderstood me, i'm french and my english is a bit rusty.. :/

**Comment by manuelgu** [comment]
@Joapple could you please try a fresh Spigot server with DiscordMC and **without** PlugMan, then upload an error log to hastebin.com and also attach a "/discord debug" (if possible). Thanks :)

**Comment by Joapple** [comment]
Okay just to reconfirm, it works on all my server EXCEPT skyblock for some reason, here is the discord debug for a new generated paperclip server (that's what we have on skyblock) only discord is loaded and actually working.. 
https://hastebin.com/diguzaholo

**Comment by manuelgu** [comment]
Could you update to 1.4.12 & attach a latest error log? They may seem very similar but it is important that I get the **very latest** one. Thanks!

**Comment by Joapple** [comment]
I thought i had the latest one, i downloaded from spigot 2 days ago...

**Edit**: oops, didn't see you updated today :3

**Comment by Joapple** [comment]
Since i have some players that are online on the server and i can't restart it like that everytime, i made an exact copy of the server, except it's called test. Same machine, same host. It's still happening, but now i can restart the server many times if i need. Every time it throws that error. I suspect imcompatibility with a plugin, but which one? lol i have 95 plugins loaded..
<details><summary>Show stack trace</summary><pre><code>
[19:15:19] [Server thread/INFO]: [DiscordMC] Enabling DiscordMC v1.4.12
[19:15:19] [Server thread/WARN]: 2017-03-09 19:15:19.191:INFO::Server thread: Logging initialized @24094ms to org.eclipse.jetty.util.log.StdErrLog
[19:15:19] [Server thread/ERROR]: Error occurred while enabling DiscordMC v1.4.12 (Is it up to date?)
java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonFactory.requiresPropertyOrdering()Z
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:564) ~[?:?]
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:474) ~[?:?]
	at sx.blah.discord.api.internal.DiscordUtils.<clinit>(DiscordUtils.java:54) ~[?:?]
	at sx.blah.discord.api.events.EventDispatcher.<init>(EventDispatcher.java:28) ~[?:?]
	at sx.blah.discord.api.internal.DiscordClientImpl.<init>(DiscordClientImpl.java:118) ~[?:?]
	at sx.blah.discord.api.ClientBuilder.build(ClientBuilder.java:199) ~[?:?]
	at eu.manuelgu.discordmc.DiscordMC.onEnable(DiscordMC.java:124) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[patched_1.11.2.jar:git-Paper-1057]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.11.2.jar:git-Paper-1057]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.11.2.jar:git-Paper-1057]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:378) [patched_1.11.2.jar:git-Paper-1057]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:328) [patched_1.11.2.jar:git-Paper-1057]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:437) [patched_1.11.2.jar:git-Paper-1057]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:398) [patched_1.11.2.jar:git-Paper-1057]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:336) [patched_1.11.2.jar:git-Paper-1057]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:276) [patched_1.11.2.jar:git-Paper-1057]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:603) [patched_1.11.2.jar:git-Paper-1057]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[19:15:19] [Server thread/INFO]: [DiscordMC] Disabling DiscordMC v1.4.12
[19:15:19] [Server thread/ERROR]: Error occurred while disabling DiscordMC v1.4.12 (Is it up to date?)
java.lang.NullPointerException
	at eu.manuelgu.discordmc.DiscordMC.onDisable(DiscordMC.java:164) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273) ~[patched_1.11.2.jar:git-Paper-1057]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344) [patched_1.11.2.jar:git-Paper-1057]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:320) [patched_1.11.2.jar:git-Paper-1057]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.11.2.jar:git-Paper-1057]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:378) [patched_1.11.2.jar:git-Paper-1057]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:328) [patched_1.11.2.jar:git-Paper-1057]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:437) [patched_1.11.2.jar:git-Paper-1057]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:398) [patched_1.11.2.jar:git-Paper-1057]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:336) [patched_1.11.2.jar:git-Paper-1057]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:276) [patched_1.11.2.jar:git-Paper-1057]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:603) [patched_1.11.2.jar:git-Paper-1057]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
</code></pre></details>

**Comment by manuelgu** [comment]
>  lol i have 95 plugins loaded..

..well. Try with a **fresh** Spigot server w/out any plugins.

**Comment by Joapple** [comment]
Yeah that's why i said i suspect incomptability with a plugin as a fresh server it works, or my creative server that has around 45 plugins works, only my skyblock it doesn't work. So it's not a "host" issue. It's a plugin issue on my skyblock server, but i don't know which one.

**Comment by Joapple** [comment]
I can try to unload 1by1 and find it, but it will take a while .. Since i can't plugman discord, i'll have to fully restart the server everytime. I'll compare plugins from my creative server and load those one only. If it works, i'll load them back, i will have less to do.

**Comment by manuelgu** [comment]
Yeah it is definitely an incompatibility with a (probably very old) plugin which uses an older version of [fasterxml/jackson](https://github.com/FasterXML/jackson). Not much I can do about it unfortunately, DiscordMC looks for a dependency of that in the classpath and only finds an older version.

**Comment by Joapple** [comment]
I found it, it was drive backup, i just made it depend DiscordMC so discord load first, then load drivebackup. This will fix my issue and the plugins now works on my skyblock server! Thanks for trying tho!
