### ISSUE TITLE
Exception after dying twice

### ISSUE THREAD

**Issue by OasisArtisan** [manuelgu/DiscordMC#29]
After dying 2 times while the death messages are enabled i always get this exception.

[19:55:05] [Async Chat Thread - #1/INFO]: [0;36;1m[[0;37;1m[0;31;22mMotherOfAllNoobs[m[0;36;1m] ,,,[m
[19:56:22] [RequestBuffer Initial Executor/ERROR]: [DiscordMC] Critical issue while sending message.. See stacktrace below
[19:56:22] [RequestBuffer Initial Executor/WARN]: sx.blah.discord.util.DiscordException: Error on request to https://discordapp.com/api/channels/297900394674257927/messages. Received response code 400. With response text: {"code": 50006, "message": "Cannot send an empty message"}
[19:56:22] [RequestBuffer Initial Executor/WARN]: 	at sx.blah.discord.api.internal.Requests$Request.request(Requests.java:310)
[19:56:22] [RequestBuffer Initial Executor/WARN]: 	at sx.blah.discord.api.internal.Requests$Request.request(Requests.java:244)
[19:56:22] [RequestBuffer Initial Executor/WARN]: 	at sx.blah.discord.api.internal.Requests$Request.makeRequest(Requests.java:233)
[19:56:22] [RequestBuffer Initial Executor/WARN]: 	at sx.blah.discord.api.internal.Requests$Request.makeRequest(Requests.java:187)
[19:56:22] [RequestBuffer Initial Executor/WARN]: 	at sx.blah.discord.api.internal.Requests$Request.makeRequest(Requests.java:133)
[19:56:22] [RequestBuffer Initial Executor/WARN]: 	at sx.blah.discord.api.internal.Requests$Request.makeRequest(Requests.java:125)
[19:56:22] [RequestBuffer Initial Executor/WARN]: 	at sx.blah.discord.handle.impl.obj.Channel.sendMessage(Channel.java:608)
[19:56:22] [RequestBuffer Initial Executor/WARN]: 	at sx.blah.discord.util.MessageBuilder.build(MessageBuilder.java:215)
[19:56:22] [RequestBuffer Initial Executor/WARN]: 	at eu.manuelgu.discordmc.MessageAPI.lambda$sendToDiscord$3(MessageAPI.java:97)
[19:56:22] [RequestBuffer Initial Executor/WARN]: 	at sx.blah.discord.util.RequestBuffer$RequestFuture$RequestCallable.call(RequestBuffer.java:271)
[19:56:22] [RequestBuffer Initial Executor/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[19:56:22] [RequestBuffer Initial Executor/WARN]: 	at sx.blah.discord.util.RequestBuffer$RequestFuture.run(RequestBuffer.java:246)
[19:56:22] [RequestBuffer Initial Executor/WARN]: 	at sx.blah.discord.util.RequestBuffer$RequestFuture.access$200(RequestBuffer.java:147)
[19:56:22] [RequestBuffer Initial Executor/WARN]: 	at sx.blah.discord.util.RequestBuffer.lambda$request$0(RequestBuffer.java:32)
[19:56:22] [RequestBuffer Initial Executor/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[19:56:22] [RequestBuffer Initial Executor/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[19:56:22] [RequestBuffer Initial Executor/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by manuelgu** [comment]
It tried to send an empty message. Are you using any plugin that modifies the death message or similar?

**Comment by OasisArtisan** [comment]
I have essentials and pvpmanager which might be changing the death messages and this exception occurs a lot randomly and it breaks the connection between the server and discord for a while. Is there a way to make it compatible with custom death messages? that logically shouldn't be a problem. thanks for the fast response.
