### ISSUE TITLE
Cannot send mention messages unless they have nickname on Discord

### ISSUE THREAD

**Issue by austinhuang0131** [manuelgu/DiscordMC#31]
```
[06:54:00 WARN]: 1530474 [Event Dispatcher Handler] ERROR sx.blah.discord.Discord4J - Unhandled exception caught dispatching event MessageReceivedEvent

[06:54:00 WARN]: java.util.NoSuchElementException: No value present
[06:54:00 WARN]:        at java.util.Optional.get(Optional.java:135)
[06:54:00 WARN]:        at eu.manuelgu.discordmc.listener.DiscordEventListener.userChat(DiscordEventListener.java:66)
[06:54:00 WARN]:        at sun.reflect.GeneratedMethodAccessor205.invoke(Unknown Source)
[06:54:00 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[06:54:00 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[06:54:00 WARN]:        at sx.blah.discord.api.events.EventDispatcher.lambda$null$11(EventDispatcher.java:376)
[06:54:00 WARN]:        at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[06:54:00 WARN]:        at sx.blah.discord.api.events.EventDispatcher.lambda$null$12(EventDispatcher.java:374)
[06:54:00 WARN]:        at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
[06:54:00 WARN]:        at sx.blah.discord.api.events.EventDispatcher.lambda$null$13(EventDispatcher.java:373)
[06:54:00 WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
[06:54:00 WARN]:        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[06:54:00 WARN]:        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
[06:54:00 WARN]:        at java.util.concurrent.ConcurrentHashMap$EntrySpliterator.forEachRemaining(ConcurrentHashMap.java:3606)
[06:54:00 WARN]:        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
[06:54:00 WARN]:        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
[06:54:00 WARN]:        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
[06:54:00 WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
[06:54:00 WARN]:        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[06:54:00 WARN]:        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
[06:54:00 WARN]:        at sx.blah.discord.api.events.EventDispatcher.lambda$dispatch$17(EventDispatcher.java:372)
[06:54:00 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[06:54:00 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[06:54:00 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[06:54:00 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[06:54:00 WARN]:        at java.lang.Thread.run(Thread.java:745)
```

**Comment by manuelgu** [comment]
Thanks! Will be fixed in the next version.

`// NOTE #getDisplayName(IGuild)`
