### ISSUE TITLE
java.lang.ClassNotFoundException: gnu.trove.set.hash.THashSet

### ISSUE THREAD

**Issue by egro5** [manuelgu/DiscordMC#36]
This appears to be similar to issue #10  

```
java.lang.NoClassDefFoundError: gnu/trove/set/hash/THashSet
java.lang.ClassNotFoundException: gnu.trove.set.hash.THashSet
```

I get this error on server start and the plugin does not work.  I'm using DiscordMC 1.4.12, Spigot 1.11.2, and Ubuntu 16.04.2

The command `/discord debug` returns only `/discord <args>`

```
[14:31:00] [Server thread/INFO]: [DiscordMC] Enabling DiscordMC v1.4.12
[14:31:00] [Server thread/ERROR]: Error occurred while enabling DiscordMC v1.4.12 (Is it up to date?                                                                      )
java.lang.NoClassDefFoundError: gnu/trove/set/hash/THashSet
        at eu.manuelgu.discordmc.DiscordMC.onEnable(DiscordMC.java:107) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[minecraft_server.jar:                                                                      git-Bukkit-6e3cec8]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) [minecraf                                                                      t_server.jar:git-Bukkit-6e3cec8]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [minecra                                                                      ft_server.jar:git-Bukkit-6e3cec8]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:361) [minecraft                                                                      _server.jar:git-Bukkit-6e3cec8]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:323) [minecraf                                                                      t_server.jar:git-Bukkit-6e3cec8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:411) [minecraft_serv                                                                      er.jar:git-Bukkit-6e3cec8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:372) [minecraft_serv                                                                      er.jar:git-Bukkit-6e3cec8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:327) [minecraft_serv                                                                      er.jar:git-Bukkit-6e3cec8]
        at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:244) [minecraft_s                                                                      erver.jar:git-Bukkit-6e3cec8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:521) [minecraft_se                                                                      rver.jar:git-Bukkit-6e3cec8]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.ClassNotFoundException: gnu.trove.set.hash.THashSet
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[minecraft                                                                      _server.jar:git-Bukkit-6e3cec8]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[minecraft                                                                      _server.jar:git-Bukkit-6e3cec8]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
        ... 12 more
```

**Comment by manuelgu** [comment]
What environment do you run on? (Linux, Windows, version etc)

**Comment by egro5** [comment]
Ubuntu 16.04.2

**Comment by egro5** [comment]
Also it's on a VPS.  Not sure if that matters.

**Comment by manuelgu** [comment]
https://www.dropbox.com/s/yaqo4p33sbfn8k8/DiscordMC-1.4.13-SNAPSHOT.jar?dl=1

How about this version?

**Comment by egro5** [comment]
Yeah, that seems to work!
