### ISSUE TITLE
DiscordMC 1.5.0 Issues?

### ISSUE THREAD

**Issue by Obey23** [manuelgu/DiscordMC#42]
Hello there, so on my servers we use DiscordMC but have it on 3 servers, Hub, Prison and Survival.
The plugin works fine on Hub and Survival but just refuses to work on Prison.

> Here is what the console says on loading the plugin..
`[16:20:02] [Server thread/INFO]: [DiscordMC] Enabling DiscordMC v1.5.0
[16:20:02] [Server thread/WARN]: [Server thread] INFO org.eclipse.jetty.util.log - Logging initialized @2392947ms to org.eclipse.jetty.util.log.Slf4jLog
[16:20:02] [Server thread/WARN]: [Server thread] INFO sx.blah.discord.Discord4J - Discord4J v2.9.3 4bb34cf (https://github.com/austinv11/Discord4J)
[16:20:02] [Server thread/WARN]: [Server thread] INFO sx.blah.discord.Discord4J - A Java binding for the official Discord API, forked from the inactive https://github.com/nerd/Discord4J. Copyright (c) 2017, Licensed under GNU LGPLv3
[16:20:02] [Server thread/WARN]: [Server thread] INFO sx.blah.discord.Discord4J - Disabled audio.
[16:20:03] [Server thread/ERROR]: Error occurred while enabling DiscordMC v1.5.0 (Is it up to date?)
java.lang.VerifyError: class com.fasterxml.jackson.databind.deser.SettableBeanProperty$Delegating overrides final method getDeclaringClass.()Ljava/lang/Class;
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_161]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_161]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_161]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_161]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_161]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_161]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_161]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_161]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_161]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:195) ~[server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[server.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_161]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_161]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_161]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_161]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_161]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_161]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_161]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_161]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_161]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_161]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_161]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:195) ~[server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[server.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_161]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_161]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_161]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_161]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_161]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_161]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_161]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_161]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_161]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_161]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_161]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:195) ~[server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[server.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_161]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_161]
	at com.fasterxml.jackson.module.afterburner.deser.PropertyMutatorCollector.addStringField(PropertyMutatorCollector.java:78) ~[?:?]
	at com.fasterxml.jackson.module.afterburner.deser.DeserializerModifier.findOptimizableProperties(DeserializerModifier.java:161) ~[?:?]
	at com.fasterxml.jackson.module.afterburner.deser.DeserializerModifier.updateBuilder(DeserializerModifier.java:58) ~[?:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:236) ~[?:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:141) ~[?:?]
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:403) ~[?:?]
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349) ~[?:?]
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264) ~[?:?]
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244) ~[?:?]
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142) ~[?:?]
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:476) ~[?:?]
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:3899) ~[?:?]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3794) ~[?:?]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2929) ~[?:?]
	at sx.blah.discord.api.internal.Requests$Request.makeRequest(Requests.java:180) ~[?:?]
	at sx.blah.discord.api.internal.DiscordClientImpl.obtainGateway(DiscordClientImpl.java:371) ~[?:?]
	at sx.blah.discord.api.internal.DiscordClientImpl.login(DiscordClientImpl.java:394) ~[?:?]
	at eu.manuelgu.discordmc.DiscordMC.onEnable(DiscordMC.java:137) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.reload(CraftServer.java:741) [server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.Bukkit.reload(Bukkit.java:535) [server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-21fe707-e1ebe52]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

Thanks anyways.

Best regards,
Obey

**Comment by Obey23** [comment]
Some other info, we have a custom /discord command that shows our discord link to the player, so i have to use /discordmc:discord to do the commands. When i try any command, it sends this:

`/discordmc:discord <args>`

**Comment by manuelgu** [comment]
There is another plugin using a dependency in an older / newer version and they are conflicting. I'll troubleshoot and get back to you as soon as possible

**Comment by Obey23** [comment]
I do use the plugin for stuff in Skript, mainly making the console do the "/discordmc:discord send" command but thats about all. I also have 131 plugins and 8 scripts running so i have no clue what it could be. Thanks anyways!

**Comment by Obey23** [comment]
I might have what it is.

**Comment by Obey23** [comment]
I indeed found what it was, there are compatibility issues with Vixio extension to Skript. 
Cheers for everything though,

Best regards,
Obey

**Comment by manuelgu** [comment]
Oh, that's good news. That's the one with a conflicting dependency :smiley:
